// Generated by CoffeeScript 1.10.0

/*
Created by MIROOF on 04/03/2015
Virtual gamepad application
 */

(function() {
  var app, config, express, gamepad_hub, gp_hub, https, fs, server, io, kb_hub, keyboard_hub, log, path, port, suffix, touchpad_hub, tp_hub;

  path = require('path');
  express = require('express');
  app = express();
  https = require('https');
  fs = require('fs');

  // Read settings and required modules
  config = require('./config.json');
  log = require('./lib/log');

  // SSL settings for HTTPS server
  var options = {
    key: fs.readFileSync(path.join(__dirname, 'ssl', 'key.pem')),
    cert: fs.readFileSync(path.join(__dirname, 'ssl', 'cert.pem')),
    // If you have a CA certificate, enable the following line
    // ca: fs.readFileSync(path.join(__dirname, 'ssl', 'ca_bundle.crt'))
  };

  // Create HTTPS server
  server = https.createServer(options, app);

  // Connect Socket.IO to HTTPS server
  io = require('socket.io')(server);

  // Load controller-related modules
  gamepad_hub = require('./app/virtual_gamepad_hub');
  gp_hub = new gamepad_hub();

  keyboard_hub = require('./app/virtual_keyboard_hub');
  kb_hub = new keyboard_hub();

  touchpad_hub = require('./app/virtual_touchpad_hub');
  tp_hub = new touchpad_hub();

  var xinput_gamepad_hub = require('./app/virtual_xinput_gamepad_hub');
  var xgp_hub = new xinput_gamepad_hub();
  
  var xboxone_gamepad_hub = require('./app/virtual_xboxone_hub');
  var xboxone_hub = new xboxone_gamepad_hub();

  var virtual_wheel_hub = require('./app/virtual_wheel_hub');
  var wh_hub = new virtual_wheel_hub();

  // Set port from environment variables or settings file
  port = process.env.PORT || config.port;

  // Determine URL suffix based on control type
  if (config.analog) {
    suffix = '?analog';
  } else {
    suffix = '';
  }

  // Redirect to main page
  app.get('/', function(req, res) {
    if (config.useGamepadByDefault) {
      return res.redirect('gamepad.html' + suffix);
    } else {
      return res.redirect('index.html' + suffix);
    }
  });

  // Serve static files
  app.use(express.json());
  app.use(express["static"](__dirname + '/public'));

  // REST API for Wheel Presets
  var presetsDir = path.join(__dirname, 'presets', 'wheel');
  
  app.get('/api/wheel-presets', function(req, res) {
    fs.readdir(presetsDir, function(err, files) {
      if (err) return res.json([]);
      var presets = files.filter(f => f.endsWith('.json')).map(f => f.replace('.json', ''));
      res.json(presets);
    });
  });

  app.get('/api/wheel-presets/:name', function(req, res) {
    var p = path.join(presetsDir, req.params.name + '.json');
    fs.readFile(p, 'utf8', function(err, data) {
      if (err) return res.status(404).json({error: 'Not found'});
      try { res.json(JSON.parse(data)); }
      catch(e) { res.status(500).json({error: 'Invalid JSON'}); }
    });
  });

  app.post('/api/wheel-presets', function(req, res) {
    var name = req.body.name;
    var configData = req.body.config;
    if (!name || !configData) return res.status(400).json({error: 'Missing name or config'});
    var p = path.join(presetsDir, name + '.json');
    fs.writeFile(p, JSON.stringify(configData, null, 2), function(err) {
      if (err) return res.status(500).json({error: 'Failed to save'});
      res.json({success: true});
    });
  });

  app.delete('/api/wheel-presets/:name', function(req, res) {
    var p = path.join(presetsDir, req.params.name + '.json');
    fs.unlink(p, function(err) {
      if (err) return res.status(500).json({error: 'Failed to delete'});
      res.json({success: true});
    });
  });

  // Socket.IO connection management
  io.on('connection', function(socket) {
    // Initialize arrays for multi-controller tracking per socket
    socket.gamePadIds = [];
    socket.xinputGamePadIds = [];
    socket.xboxOneGamePadIds = [];
    socket.wheelIds = [];
    socket.keyBoardIds = [];
    socket.touchpadIds = [];

    socket.on('disconnect', function() {
      // Disconnect all gamepads owned by this socket
      socket.gamePadIds.forEach(function(padId) {
        log('info', ' Gamepad ' + padId + ' disconnected');
        gp_hub.disconnectGamepad(padId, function() {});
      });

      // Disconnect all xinput gamepads owned by this socket
      socket.xinputGamePadIds.forEach(function(padId) {
        xgp_hub.disconnectGamepad(padId, function() {
          log('info', 'Xinput gamepad ' + padId + ' disconnected.');
        });
      });
      // Disconnect all xboxone gamepads owned by this socket
      socket.xboxOneGamePadIds.forEach(function(padId) {
        xboxone_hub.disconnectGamepad(padId, function() {
          log('info', 'Xboxone gamepad ' + padId + ' disconnected.');
        });
      });

      // Disconnect all wheels owned by this socket
      socket.wheelIds.forEach(function(padId) {
        wh_hub.disconnectWheel(padId, function() {
          log('info', 'Virtual wheel ' + padId + ' disconnected.');
        });
      });

      // Disconnect all keyboards owned by this socket
      socket.keyBoardIds.forEach(function(boardId) {
        log('info', ' Keyboard ' + boardId + ' disconnected');
        kb_hub.disconnectKeyboard(boardId, function() {});
      });

      // Disconnect all touchpads owned by this socket
      socket.touchpadIds.forEach(function(touchpadId) {
        log('info', ' Touchpad ' + touchpadId + ' disconnected');
        tp_hub.disconnectTouchpad(touchpadId, function() {});
      });

      if (socket.gamePadIds.length === 0 &&
          socket.xinputGamePadIds.length === 0 &&
          socket.xboxOneGamePadIds.length === 0 &&
          socket.wheelIds.length === 0 &&
          socket.keyBoardIds.length === 0 &&
          socket.touchpadIds.length === 0) {
        log('info', ' Unknown disconnect');
      }
    });

    // Manage Gamepad connection
    socket.on('connectGamepad', function() {
      return gp_hub.connectGamepad(function(gamePadId) {
        var ledBitField;
        ledBitField = config.ledBitFieldSequence[gamePadId];
        if (gamePadId !== -1) {
          log('info', ' connectGamepad: success (slot ' + gamePadId + ')');
          socket.gamePadIds.push(gamePadId);
          return socket.emit('gamepadConnected', {
            padId: gamePadId,
            ledBitField: ledBitField
          });
        } else {
          return log('warning', ' connectGamepad: failed');
        }
      });
    });

    // Manage Gamepad events — routes by padId in data (with backward compat)
    socket.on('padEvent', function(data) {
      log('debug', 'padEvent ' + JSON.stringify(data));
      if (!data) return;
      // Backward compat: old clients don't send padId, use first connected pad
      var targetPadId = (data.padId !== undefined) ? data.padId : socket.gamePadIds[0];
      if (targetPadId !== undefined && socket.gamePadIds.indexOf(targetPadId) !== -1) {
        return gp_hub.sendEvent(targetPadId, data);
      }
    });

    // Manage XInput Gamepad connection
    socket.on('connectXInputGamepad', function() {
      return xgp_hub.connectGamepad(function(gamePadId) {
        var ledBitField;
        ledBitField = config.ledBitFieldSequence[gamePadId];
        if (gamePadId !== -1) {
          log('info', ' connectXInputGamepad: success (slot ' + gamePadId + ')');
          socket.xinputGamePadIds.push(gamePadId);
          return socket.emit('xinputGamepadConnected', {
            padId: gamePadId,
            ledBitField: ledBitField
          });
        } else {
          return log('warning', ' connectXInputGamepad: failed');
        }
      });
    });

    // Manage XInput Gamepad events — now routes by padId in data
    socket.on('xinputPadEvent', function(data) {
      log('debug', 'xinputPadEvent ' + JSON.stringify(data));
      if (data && data.padId !== undefined && socket.xinputGamePadIds.indexOf(data.padId) !== -1) {
        xgp_hub.sendEvent(data.padId, data);
      }
    });

    socket.on('connectXboxOneGamepad', function() {
      xboxone_hub.connectGamepad(function(gamePadId) {
        if (gamePadId !== -1) {
          socket.xboxOneGamePadIds.push(gamePadId);
          return socket.emit('xboxOneGamepadConnected', {
            padId: gamePadId
          });
        } else {
          return socket.emit('xboxOneGamepadConnected', {
            padId: -1
          });
        }
      }, function(gamePadId, duration) {
        // Vibrate callback
        if (socket.xboxOneGamePadIds.indexOf(gamePadId) !== -1) {
          socket.emit('xboxOneVibrate', { duration: duration });
        }
      });
    });

    socket.on('xboxOnePadEvent', function(data) {
      log('debug', 'xboxOnePadEvent ' + JSON.stringify(data));
      if (data && data.padId !== undefined && socket.xboxOneGamePadIds.indexOf(data.padId) !== -1) {
        xboxone_hub.sendEvent(data.padId, data);
      }
    });

    // Manage Wheel connection
    socket.on('connectWheel', function() {
      return wh_hub.connectWheel(function(gamePadId) {
        var ledBitField = config.ledBitFieldSequence[gamePadId];
        if (gamePadId !== -1) {
          log('info', ' connectWheel: success (slot ' + gamePadId + ')');
          socket.wheelIds.push(gamePadId);
          return socket.emit('wheelConnected', {
            padId: gamePadId,
            ledBitField: ledBitField
          });
        } else {
          return log('warning', ' connectWheel: failed');
        }
      });
    });

    socket.on('wheelEvent', function(data) {
      log('debug', 'wheelEvent ' + JSON.stringify(data));
      if (data && data.padId !== undefined && socket.wheelIds.indexOf(data.padId) !== -1) {
        wh_hub.sendEvent(data.padId, data);
      }
    });

    // Manage Keyboard connection
    socket.on('connectKeyboard', function() {
      return kb_hub.connectKeyboard(function(keyBoardId) {
        if (keyBoardId !== -1) {
          log('info', ' connectKeyboard: success (slot ' + keyBoardId + ')');
          socket.keyBoardIds.push(keyBoardId);
          return socket.emit('keyboardConnected', {
            boardId: keyBoardId
          });
        } else {
          return log('info', ' connectKeyboard: failed');
        }
      });
    });

    // Manage Keyboard events (with backward compat)
    socket.on('boardEvent', function(data) {
      log('debug', 'boardEvent ' + JSON.stringify(data));
      if (!data) return;
      var targetBoardId = (data.boardId !== undefined) ? data.boardId : socket.keyBoardIds[0];
      if (targetBoardId !== undefined && socket.keyBoardIds.indexOf(targetBoardId) !== -1) {
        return kb_hub.sendEvent(targetBoardId, data);
      }
    });

    // Manage Touchpad connection
    socket.on('connectTouchpad', function() {
      return tp_hub.connectTouchpad(function(touchpadId) {
        if (touchpadId !== -1) {
          log('info', ' connectTouchpad: success (slot ' + touchpadId + ')');
          socket.touchpadIds.push(touchpadId);
          return socket.emit('touchpadConnected', {
            touchpadId: touchpadId
          });
        } else {
          return log('info', ' connectTouchpad: failed');
        }
      });
    });

    // Manage Touchpad events (with backward compat)
    socket.on('touchpadEvent', function(data) {
      log('debug', 'touchpadEvent ' + JSON.stringify(data));
      if (!data) return;
      var targetTouchpadId = (data.touchpadId !== undefined) ? data.touchpadId : socket.touchpadIds[0];
      if (targetTouchpadId !== undefined && socket.touchpadIds.indexOf(targetTouchpadId) !== -1) {
        return tp_hub.sendEvent(targetTouchpadId, data);
      }
    });

    // Controller status endpoint — returns slot occupancy for all controller types
    socket.on('getControllerStatus', function() {
      return socket.emit('controllerStatus', {
        gamepads: gp_hub.getStatus(),
        xinputGamepads: xgp_hub.getStatus(),
        xboxOneGamepads: xboxone_hub.getStatus(),
        wheels: wh_hub.getStatus(),
        keyboards: kb_hub.getStatus(),
        touchpads: tp_hub.getStatus()
      });
    });

    // Disconnect a specific controller by type and padId
    socket.on('disconnectController', function(data) {
      if (!data || data.padId === undefined || !data.type) return;
      var padId = data.padId;
      var idx;

      switch (data.type) {
        case 'gamepad':
          idx = socket.gamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.gamePadIds.splice(idx, 1);
            gp_hub.disconnectGamepad(padId, function() {
              log('info', ' Gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'gamepad', padId: padId });
            });
          }
          break;
        case 'xinputGamepad':
          idx = socket.xinputGamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.xinputGamePadIds.splice(idx, 1);
            xgp_hub.disconnectGamepad(padId, function() {
              log('info', 'Xinput gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'xinputGamepad', padId: padId });
            });
          }
          break;
        case 'xboxOneGamepad':
          idx = socket.xboxOneGamePadIds.indexOf(padId);
          if (idx !== -1) {
            socket.xboxOneGamePadIds.splice(idx, 1);
            xboxone_hub.disconnectGamepad(padId, function() {
              log('info', 'Xboxone gamepad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'xboxOneGamepad', padId: padId });
            });
          }
          break;
        case 'wheel':
          idx = socket.wheelIds.indexOf(padId);
          if (idx !== -1) {
            socket.wheelIds.splice(idx, 1);
            wh_hub.disconnectWheel(padId, function() {
              log('info', 'Virtual wheel ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'wheel', padId: padId });
            });
          }
          break;
        case 'keyboard':
          idx = socket.keyBoardIds.indexOf(padId);
          if (idx !== -1) {
            socket.keyBoardIds.splice(idx, 1);
            kb_hub.disconnectKeyboard(padId, function() {
              log('info', ' Keyboard ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'keyboard', padId: padId });
            });
          }
          break;
        case 'touchpad':
          idx = socket.touchpadIds.indexOf(padId);
          if (idx !== -1) {
            socket.touchpadIds.splice(idx, 1);
            tp_hub.disconnectTouchpad(padId, function() {
              log('info', ' Touchpad ' + padId + ' manually disconnected');
              socket.emit('controllerDisconnected', { type: 'touchpad', padId: padId });
            });
          }
          break;
      }
    });
  });

  // Error management
  server.on('error', function(err) {
    if (err.hasOwnProperty('errno')) {
      switch (err.errno) {
        case "EACCES":
          log('error', " You don't have permissions to open port " + port + ". " + "For ports smaller than 1024, you need root privileges.");
      }
    }
    throw err;
  });

  // Start listening to requests
  server.listen(port, function() {
    return log('info', "󰌗 Listening on " + port);
  });

}).call(this);
