// Generated by CoffeeScript 2.7.0
(function() {
  /*
  Virtual XInput Gamepad Hub class
  Manages multiple xinput gamepad slots
  */
  var config, log, num_gamepads, virtual_xinput_gamepad_hub, xinput_gamepad;

  xinput_gamepad = require('./virtual_xinput_gamepad');

  log = require('../lib/log');

  config = require('../config');

  num_gamepads = config.maxXinputGamepads || config.ledBitFieldSequence.length;

  virtual_xinput_gamepad_hub = class virtual_xinput_gamepad_hub {
    constructor() {
      var i, j, ref;
      this.gamepads = [];
      for (i = j = 0, ref = num_gamepads - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
        this.gamepads[i] = void 0;
      }
    }

    connectGamepad(callback) {
      var freeSlot, padId;
      padId = 0;
      freeSlot = false;
      while (!freeSlot && padId < num_gamepads) {
        if (!this.gamepads[padId]) {
          freeSlot = true;
        } else {
          padId++;
        }
      }
      if (!freeSlot) {
        log('warning', "Couldn't add new xinput gamepad: no slot left.");
        return callback(-1);
      } else {
        log('info', 'Creating and connecting to xinput gamepad number ' + padId);
        this.gamepads[padId] = new xinput_gamepad();
        return this.gamepads[padId].connect(function() {
          return callback(padId);
        }, function(err) {
          this.gamepads[padId] = void 0;
          log('error', "Couldn't connect to xinput gamepad:\n" + JSON.stringify(err));
          return callback(-1);
        });
      }
    }

    disconnectGamepad(padId, callback) {
      if (this.gamepads[padId]) {
        return this.gamepads[padId].disconnect(() => {
          this.gamepads[padId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(padId, event) {
      if (this.gamepads[padId]) {
        return this.gamepads[padId].sendEvent(event);
      }
    }

  };

  module.exports = virtual_xinput_gamepad_hub;

}).call(this);
