// Generated by CoffeeScript 2.7.0
(function() {
  /*
  Virtual touchpad hub class
  */
  var config, log, num_touchpads, touchpad, virtual_touchpad_hub;

  touchpad = require('./virtual_touchpad');

  log = require('../lib/log');

  config = require('../config');

  num_touchpads = config.maxTouchpads || 4;

  virtual_touchpad_hub = class virtual_touchpad_hub {
    constructor() {
      this.touchpads = [];
    }

    connectTouchpad(callback) {
      var touchpadId;
      touchpadId = this.touchpads.length;
      // Check if max touchpads reached
      if (touchpadId >= num_touchpads) {
        log('warning', "Couldn't add new touchpad: no slot left.");
        callback(-1);
        return;
      }
      // Create and connect the touchpad
      log('info', 'Creating and connecting to touchpad number ' + touchpadId);
      this.touchpads[touchpadId] = new touchpad();
      return this.touchpads[touchpadId].connect(function() {
        return callback(touchpadId);
      }, function(err) {
        log('error', "Couldn't connect to touchpad:\n" + JSON.stringify(err));
        return callback(-1);
      });
    }

    disconnectTouchpad(touchpadId, callback) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].disconnect(() => {
          this.touchpads[touchpadId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(touchpadId, event) {
      if (this.touchpads[touchpadId]) {
        return this.touchpads[touchpadId].sendEvent(event);
      }
    }

  };

  module.exports = virtual_touchpad_hub;

}).call(this);
