// Generated by CoffeeScript 2.7.0
(function() {
  /*
  Created by roba91 on 15/08/2016
  Virtual keyboard hub class
  */
  var config, keyboard, log, num_keyboards, virtual_keyboard_hub;

  keyboard = require('./virtual_keyboard');

  log = require('../lib/log');

  config = require('../config');

  num_keyboards = config.maxKeyboards || 4;

  virtual_keyboard_hub = class virtual_keyboard_hub {
    constructor() {
      this.keyboards = [];
    }

    connectKeyboard(callback) {
      var boardId;
      boardId = this.keyboards.length;
      // Check if max keyboards reached
      if (boardId >= num_keyboards) {
        log('warning', "Couldn't add new keyboard: no slot left.");
        callback(-1);
        return;
      }
      // Create and connect the keyboard
      log('info', 'Creating and connecting to keyboard number' + boardId);
      this.keyboards[boardId] = new keyboard();
      return this.keyboards[boardId].connect(function() {
        return callback(boardId);
      }, function(err) {
        log('error', "Couldn't connect to keyboard:\n" + JSON.stringify(err));
        return callback(-1);
      });
    }

    disconnectKeyboard(boardId, callback) {
      if (this.keyboards[boardId]) {
        return this.keyboards[boardId].disconnect(() => {
          this.keyboards[boardId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(boardId, event) {
      if (this.keyboards[boardId]) {
        return this.keyboards[boardId].sendEvent(event);
      }
    }

  };

  module.exports = virtual_keyboard_hub;

}).call(this);
