// Generated by CoffeeScript 2.7.0
(function() {
  /*
  Created by MIROOF on 04/03/2015
  Virtual gamepad hub class
  */
  var config, gamepad, log, num_gamepads, virtual_gamepad_hub;

  gamepad = require('./virtual_gamepad');

  log = require('../lib/log');

  config = require('../config');

  num_gamepads = config.maxGamepads || config.ledBitFieldSequence.length;

  // ledBitFieldSequence should be an array of 'bit fields'.
  // the bit fields are numbers from 0-15, resulting in the following LED arrangements:
  //  0 - ....
  //  1 - *...
  //  2 - .*..
  //  3 - **..
  //  4 - ..*.
  //  5 - *.*.
  //  6 - .**.
  //  7 - ***.
  //  8 - ...*
  //  9 - *..*
  // 10 - .*.*
  // 11 - **.*
  // 12 - ..**
  // 13 - *.**
  // 14 - .***
  // 15 - ****
  virtual_gamepad_hub = class virtual_gamepad_hub {
    constructor() {
      var i, j, ref;
      this.gamepads = [];
      for (i = j = 0, ref = num_gamepads - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
        this.gamepads[i] = void 0;
      }
    }

    connectGamepad(callback) {
      var freeSlot, padId;
      padId = 0;
      freeSlot = false;
      while (!freeSlot && padId < num_gamepads) {
        if (!this.gamepads[padId]) {
          freeSlot = true;
        } else {
          padId++;
        }
      }
      if (!freeSlot) {
        log('warning', "Couldn't add new gamepad: no slot left.");
        return callback(-1);
      } else {
        // Create and connect the gamepad
        log('info', 'Creating and connecting to gamepad number ' + padId);
        this.gamepads[padId] = new gamepad();
        return this.gamepads[padId].connect(function() {
          return callback(padId);
        }, function(err) {
          this.gamepads[padId] = void 0;
          log('error', "Couldn't connect to gamepad:\n" + JSON.stringify(err));
          return callback(-1);
        });
      }
    }

    disconnectGamepad(padId, callback) {
      if (this.gamepads[padId]) {
        return this.gamepads[padId].disconnect(() => {
          this.gamepads[padId] = void 0;
          return callback();
        });
      }
    }

    sendEvent(padId, event) {
      if (this.gamepads[padId]) {
        return this.gamepads[padId].sendEvent(event);
      }
    }

    getStatus() {
      var i, j, occupied, ref, slots, used;
      slots = [];
      used = 0;
      for (i = j = 0, ref = num_gamepads - 1; (0 <= ref ? j <= ref : j >= ref); i = 0 <= ref ? ++j : --j) {
        occupied = !!this.gamepads[i];
        slots.push(occupied);
        if (occupied) {
          used++;
        }
      }
      return {
        slots: slots,
        total: num_gamepads,
        used: used,
        free: num_gamepads - used
      };
    }

  };

  module.exports = virtual_gamepad_hub;

}).call(this);
